name: Run ksh Script

on: [push]

jobs:
  run-ksh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute KornShell Script
        shell: ksh {0} # Specifies ksh as the shell
        run: ./guessinggame.sh # Path to your ksh script in the repo
        
